 SELECT distinct SCTNUM FROM AS400CPUTILIZSUBSEIBS where ROWNUM < 1000;
 
 select * from AS400CPUTILXPRCIBS where SUBSTR(DTETIM,3,2)='09';
 
 select * from AS400DISKSSPACEIBS;
 
 DROP TABLE BOD_RED_LATENCIA_COMPENSACION;