select substr(DTETIM,1,2) YY,SUBSTR(DTETIM,3,2) MM, SUBSTR(DTETIM,5,2) DD, SUBSTR(DTETIM,7,2) HH,
CASE WHEN JBPRTY<50 THEN 'ALTA' ELSE 'BAJA' END PRIORIDAD,
JBTYPE,
ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY JBTCPU/INTSEC/1000),2) CPU,
ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY JBTCPU/INTSEC/SCTNUM/1000),2) CPU_BY_SCTNUM
from AS400CPUTILIZEIBS 
--where ROWNUM < 10000
GROUP BY
substr(DTETIM,1,2),
SUBSTR(DTETIM,3,2), 
SUBSTR(DTETIM,5,2), 
SUBSTR(DTETIM,7,2),
CASE WHEN JBPRTY<50 THEN 'ALTA' ELSE 'BAJA' END,
JBTYPE
;

SELECT (5*7*21)/5 FROM DUAL;

 SELECT * from AS400CPUTILIZEIBS where ROWNUM < 100;
 
 SELECT * FROM AS400CPUTILIZSUBSEIBS where ROWNUM < 100;