SELECT DISTINCT SUBSTR(DTETIM,1,8), SCTNUM FROM AS400CPUTILIZEIBS WHERE SCTNUM IS NOT NULL ORDER BY 1;

SELECT DISTINCT SUBSTR(TAB1.DTETIM,1,8), TAB1.SCTNUM, TAB2.SCTNUM
FROM AS400CPUTILIZEIBS TAB1,  
(SELECT DISTINCT DTETIM,SCTNUM FROM AS400CPUTILIZEIBS WHERE SCTNUM IS NOT NULL AND SUBSTR(DTETIM,1,4)='1512') TAB2
WHERE TAB1.SCTNUM IS NULL AND SUBSTR(TAB1.DTETIM,1,8)=SUBSTR(TAB2.DTETIM,1,8)  AND SUBSTR(TAB1.DTETIM,1,4)='1512';

UPDATE AS400CPUTILIZEIBS T1
SET SCTNUM = (SELECT DISTINCT AVG(SCTNUM) FROM AS400CPUTILIZEIBS T2
              WHERE T2.SCTNUM IS NOT NULL AND SUBSTR(DTETIM,1,8)= SUBSTR(T1.DTETIM,1,8))
WHERE SUBSTR(T1.DTETIM,1,4)='1606';

SELECT DISTINCT SUBSTR(DTETIM,1,8), SCTNUM FROM AS400CPUTILIZEIBS
WHERE SCTNUM IS NULL AND SUBSTR(DTETIM,1,4) = '1511';

CREATE VIEW AS400_VIEW_SCTNUM AS SELECT DISTINCT SUBSTR(DTETIM,1,8), SCTNUM FROM AS400CPUTILIZEIBS WHERE SCTNUM IS NOT NULL;


SELECT DISTINCT SUBSTR(DTETIM,1,12), SCTNUM FROM AS400CPUTILIZEIBS WHERE SCTNUM IS NOT NULL   AND  SUBSTR(DTETIM,1,6)='160801' ORDER BY 1;

SELECT * FROM AS400CPUTILIZEIBS;
