select sbusstr(DTETIM,1,2) YY, SUBSTR(DTETIM,3,2) MM, SUBSTR(DTETIM,5,2) DD from AS400CPUTILXPRCIBS;

SELECT DISTINCT SUBSTR(DTETIM,1,4),  SCTNUM FROM AS400CPUTILIZEIBS WHERE SUBSTR(DTETIM,1,2)='15' AND SUBSTR(DTETIM,3,2) IN ('11','12')  ;

SELECT DISTINCT SUBSTR(DTETIM,1,8),  SCTNUM FROM AS400CPUTILIZEIBS ORDER BY SUBSTR(DTETIM,1,8);  

JUNIO Y JULIO CORRRESPONDE OTRO EQUIPO

16 ISB PRODUCCION
6  INTERNET BANKIN
16 PROCESADORES FISICOS 23 PROCESADORES VIRTUALES.
32 PROCESADORES AGOSTO? DESCARTAR SI NO SON MUCHOS REGISTROS..
CAMPOS EN BLANCO SE TOMAN LOS VALORES QUE TENIAN LOS REGISTROS.


NOVIEMBRE DICIEMBRE AGOSTO SEPTIEMBRE PARA EL INFORME
AGOSTO Y SEPTIEMBRE CORRESPONDE AL EQUIPO QUE REQUIERE EL ESTUDIO.