SELECT  DISTINCT RECORDING_TIME FROM BOD_DLOG;

SELECT SERVICIO, SERVIDOR FROM BOD_METRICAS3 WHERE SERVIDOR='BODBDAPPS8';

SELECT DISTINCT SERVICIO, SERVIDOR FROM BOD_METRICAS  UNION
SELECT DISTINCT SERVICIO, SERVIDOR FROM BOD_METRICAS2 UNION
SELECT DISTINCT SERVICIO, SERVIDOR FROM BOD_METRICAS3;

SELECT DISTINCT SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RECORDING_TIME,'/2016','/16'),' 0:',' 00:'),' 1:',' 01:'),' 2:',' 02:'),' 3:',' 03:'),' 4:',' 04:'),' 5:',' 05:'),' 6:',' 06:'),' 7:',' 07:'),' 8:',' 08:'),' 9:',' 09:'),1,14) FROM BOD_DLOG;

UPDATE BOD_METRICAS3 SET SERVICIO= 'sipr3' WHERE SERVIDOR='TIACAAPP01';

SELECT * FROM BOD_METRICAS WHERE OBJETO LIKE '%Disk%' AND IDLETIME_PCT_AVG > 100;