--------------------------------------------------------
-- Archivo creado  - jueves-octubre-27-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AS400CPUSUBSYS_TEMP
--------------------------------------------------------
INSERT INTO AS400CPUSUBSYS_TEMP
(SELECT * FROM AS400CPUTILIZSUBSEIBS
WHERE SUBSTR(DTETIM,1,4) IN ('1609') AND SCTNUM IS NOT NULL );

SELECT DISTINCT SUBSTR(DTETIM,1,4) FROM AS400CPUSUBSYS_TEMP;

 DROP TABLE AS400CPUSUBSYS_TEMP;
 
  CREATE TABLE "SYSTEM"."AS400CPUSUBSYS_TEMP" 
   (	"DTETIM" NUMBER, 
	"INTSEC" NUMBER, 
	"JBSSYS" VARCHAR2(40 BYTE), 
	"JBNAME" VARCHAR2(80 BYTE), 
	"JBUSER" VARCHAR2(40 BYTE), 
	"JBTCPU" NUMBER, 
	"JBPRTY" VARCHAR2(20 BYTE), 
	"SCTNUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
