SELECT  
CLASE & "|" & SPACE(6-LEN(FACTURA_TOTAL.ID)) & FACTURA_TOTAL.ID &" | "&  
SPACE(6-LEN(FACTURA_TOTAL.NRO_FACTURA)) & FACTURA_TOTAL.NRO_FACTURA &" | "&    
SPACE(10-LEN(FACTURA_TOTAL.FE_EMISION)) & FACTURA_TOTAL.FE_EMISION &" | "&   
SPACE(12-LEN(FACTURA_TOTAL.MONTO)) & FACTURA_TOTAL.MONTO &"|" AS DEUDA,
IIF(SUM(PAGOS.MONTO)=0,FACTURA_TOTAL.MONTO, FACTURA_TOTAL.MONTO-SUM(PAGOS.MONTO))AS PAGOS
FROM FACTURA_TOTAL   
LEFT JOIN PAGOS
ON FACTURA_TOTAL.ID=PAGOS.ID_DOCU
WHERE (CLASE="FT" AND 
	   FACTURA_TOTAL.[ID_EMPRESA]=IIF([TX_ID_EMPRESA]="NA",-1,[TX_ID_EMPRESA]) 
	   )
HAVING FACTURA_TOTAL.MONTO<SUM(PAGOS.MONTO)
GROUP BY 
CLASE & "|" & SPACE(6-LEN(FACTURA_TOTAL.ID)) & FACTURA_TOTAL.ID &" | "&  
SPACE(6-LEN(FACTURA_TOTAL.NRO_FACTURA)) & FACTURA_TOTAL.NRO_FACTURA &" | "&    
SPACE(10-LEN(FACTURA_TOTAL.FE_EMISION)) & FACTURA_TOTAL.FE_EMISION &" | "&   
SPACE(12-LEN(FACTURA_TOTAL.MONTO)) & FACTURA_TOTAL.MONTO &"|",
FACTURA_TOTAL.MONTO
UNION
SELECT
CLASE & "|" & SPACE(6-LEN(FACTURA_TOTAL.ID)) & FACTURA_TOTAL.ID &" | "&  
SPACE(6-LEN(FACTURA_TOTAL.NRO_FACTURA)) & FACTURA_TOTAL.NRO_FACTURA &" | "&    
SPACE(10-LEN(FACTURA_TOTAL.FE_EMISION)) & FACTURA_TOTAL.FE_EMISION &" | "&   
SPACE(12-LEN(FACTURA_TOTAL.MONTO)) & FACTURA_TOTAL.MONTO &"|" AS DEUDA,
IIF(SUM(PAGOS.MONTO)=0,FACTURA_TOTAL.MONTO, FACTURA_TOTAL.MONTO-SUM(PAGOS.MONTO))AS PAGOS
FROM FACTURA_TOTAL   
LEFT JOIN PAGOS
ON FACTURA_TOTAL.ID=PAGOS.ID_DOCU
WHERE (CLASE="SF"                  AND 
	   FACTURA_TOTAL.[RAZON_SOCIAL]=[TX_CLIENTE]) 
HAVING FACTURA_TOTAL.MONTO<SUM(PAGOS.MONTO)
GROUP BY
CLASE & "|" & SPACE(6-LEN(FACTURA_TOTAL.ID)) & FACTURA_TOTAL.ID &" | "&  
SPACE(6-LEN(FACTURA_TOTAL.NRO_FACTURA)) & FACTURA_TOTAL.NRO_FACTURA &" | "&    
SPACE(10-LEN(FACTURA_TOTAL.FE_EMISION)) & FACTURA_TOTAL.FE_EMISION &" | "&   
SPACE(12-LEN(FACTURA_TOTAL.MONTO)) & FACTURA_TOTAL.MONTO &"|",
FACTURA_TOTAL.MONTO;
